export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';

export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';

export const SIGNUP_USER_COMPLETED = 'SIGNUP_USER_COMPLETED';

export const SIGNUP_USER_STARTED = 'SIGNUP_USER_STARTED';

export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const LOGOUT_USER_STARTED = 'LOGOUT_USER_STARTED';

export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const LOGOUT_USER_COMPLETED = 'LOGOUT_USER_COMPLETED';

export const LOAD_USER = 'LOAD_USER';

export const LOAD_USER_STARTED = 'LOAD_USER_STARTED';

export const LOAD_USER_COMPLETED = 'LOAD_USER_COMPLETED';
