import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#181829',
  },
  textInput: {
    paddingLeft: Platform.OS === 'ios' ? 0 : 15,
    color: 'white',
    width: 30,
    fontSize: 18,
    fontWeight: 'bold',
  },

  action: {
    justifyContent: 'center',
    height: 40,
    backgroundColor: '#222232',
    margin: 8,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: Platform.OS === 'ios' ? 10 : 5,
  },

  Team: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    marginHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#4F5287',
    marginBottom: 20,
  },
  titleTeam: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    marginLeft: 10,
    color: 'white',
  },
  players: {
    justifyContent: 'center',
    borderRadius: 5,
    marginHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#999',
  },
  titlePlayers: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    marginLeft: 10,
    color: 'white',
  },
  addButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginVertical: 40,
  },
  imagePlus: {
    width: 30,
    height: 30,
    tintColor: 'white',
    marginLeft: 10,
  },
  scrollView: {
    marginBottom: 80,
  },
  containerStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
    marginHorizontal: 55,
  },
  score: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',

    width: 30,
    textAlign: 'center',
    flexShrink: 0,
  },
  scoreText: {
    color: '#C4C4C4',
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',
  },
  statsView: {
    borderRadius: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#999',
    marginTop: 20,
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginHorizontal: 20,
  },
  rowFront: {
    marginLeft: 15,
    justifyContent: 'center',
    backgroundColor: '#181829',
    height: 50,
    margin: 5,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#999',
  },
  rowFrontVisible: {
    backgroundColor: '#181829',
    borderRadius: 5,
    height: 60,
    padding: 10,
    marginBottom: 15,
  },
  rowBack: {
    alignItems: 'center',
    backgroundColor: '#181829',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
    margin: 5,
    marginBottom: 15,
    borderRadius: 5,
  },
  backRightBtn: {
    alignItems: 'flex-end',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75,
    paddingRight: 17,
  },
  backRightBtnLeft: {
    backgroundColor: '#1f65ff',
    right: 75,
    justifyContent: 'center',
  },
  backRightBtnRight: {
    backgroundColor: 'red',
    right: 0,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  trash: {
    height: 25,
    width: 25,
    marginRight: 7,
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#666',
  },
  details: {
    fontSize: 12,
    color: '#999',
  },
  image: {width: 25, height: 25, tintColor: 'white'},

  radius: {
    width: '95%',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    justifyContent: 'space-between',
  },
  noBackground: {
    borderStartColor: 'transparent',
  },
  text: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',
  },
  textTitle: {
    color: 'gray',
  },
  line: {
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    opacity: 0.05,
  },
  icon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconCountry: {marginRight: 10},
  containerText: {
    flexDirection: 'column',
  },
  viewScreen: {
    marginTop: Platform.OS === 'ios' ? 40 : 20,
    marginLeft: '25%',
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  nameScreen: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
    fontStyle: 'normal',
  },
  navigate: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginBottom: 20,
  },
  search: {
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 16,
    width: '90%',
    borderWidth: 1,
    height: 50,
    margin: 5,
    paddingHorizontal: 15,
    borderColor: '#222232',
    backgroundColor: '#222232',
    marginBottom: 30,
  },

  lastView: {height: 75},
  searchView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  swipeView: {
    marginBottom: 60,
  },
});

export default styles;
